### ISSUE TITLE
Does not support vscode v1.33.0

### ISSUE THREAD

**Issue by n0rv1n** [arichika/previewseqdiag-vscode#13]
It does not support vscode v1.33.0，can you add support for the new version?

**Comment by arichika** [comment]
I will check it. I want to support it.

**Comment by arichika** [comment]
Started to fix.  #14

**Comment by arichika** [comment]
if you try a BETA,  please try this.
https://github.com/arichika/previewseqdiag-vscode/blob/f56a81afbcfde150961b0a66674d666810a39e36/previewseqdiag-vscode-0.2.0-beta1.vsix

But I do not know what will happen... THIS IS BETA.

**Comment by arichika** [comment]
@n0rv1n i did. please update extention under ^v1.33.0
https://marketplace.visualstudio.com/items?itemName=arichika.previewseqdiag-vscode
