### ISSUE TITLE
Extension seems not working on VS1.54.3

### ISSUE THREAD

**Issue by stevealexandre** [arichika/previewseqdiag-vscode#24]
Hi dude,

It seems to be a great extension for generate diagram and shared them cross a team but the preview seems not working on the last vscode version.
![image](https://user-images.githubusercontent.com/21204359/112804981-54032e00-9075-11eb-81a5-f4e4460977ec.png)
![image](https://user-images.githubusercontent.com/21204359/112805026-5ebdc300-9075-11eb-9d9d-c0dc81817272.png)

In addition, I'm suggesting to add some "code" examples directly in your description of the extension instead of simple pictures which are small for beginners :).

**Comment by arichika** [comment]
@stevealexandre 
Oh... Thank you. I will fix.

**Comment by arichika** [comment]
@stevealexandre  I fixed it. Please update the extension to 0.3.0.
