### ISSUE TITLE
please bump the mermaid version

### ISSUE THREAD

**Issue by Spown** [arichika/previewseqdiag-vscode#27]
The current internal mermaid version of the ext is 8.9.2. the newest is 8.11. 

Particularly the old version has problems handling empty messages:

```mermaid
sequenceDiagram

activate mob
mob->>pcek:b()
activate pcek
pcek-->>mob:
mob->>pcek:c()
```

8.9.2:
![image](https://user-images.githubusercontent.com/3817672/128585521-fb3a8c90-d31d-4215-9bf7-79b53ebabccc.png)

The problem part is ``pcek-->>mob:``

But 8.11 can handle it as long as there is a new  message following the empty one:
![image](https://user-images.githubusercontent.com/3817672/128585532-1633c068-fb04-4938-912e-fc1fd461b080.png)

Thank you in advance.

**Comment by arichika** [comment]
Thank you for your patience for a long long time.
I have updated it.
 https://github.com/arichika/previewseqdiag-vscode/releases/tag/0.3.2
