### ISSUE TITLE
Update mermaid version

### ISSUE THREAD

**Issue by linus-ha** [arichika/previewseqdiag-vscode#43]
Please update the mermaid version, so that [Annotations on classes](https://mermaid-js.github.io/mermaid/#/./classDiagram?id=annotations-on-classes) can be used.

**Comment by arichika** [comment]
Thanks.

I updated mermaind to the latest version with v0.4.2 of previewseqdiag-vscode. However, the official site seems to have problems even with the latest 9.2.2.

Have a good mermaid life.

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/1038874/207205320-7288024f-56f8-4a76-8c97-f74271ca2eb3.png">

**Comment by arichika** [comment]
memo:

mermaid.min.js's bug?

OK Syntax.

```
classDiagram
class Shape{
    << interface >>
    noOfVertices
    draw()
}
class Color{
    << enumeration >>
    RED
    BLUE
    GREEN
    WHITE
    BLACK
}
```

NG Syntax.

```
classDiagram
class Shape{
    <<interface>>
    noOfVertices
    draw()
}
class Color{
    <<enumeration>>
    RED
    BLUE
    GREEN
    WHITE
    BLACK
}
```

`<<interface>>` or `<< interface >>`
