### ISSUE TITLE
empty preview

### ISSUE THREAD

**Issue by yemal** [arichika/previewseqdiag-vscode#50]
It is not clear how to start using it.
I've installed the ext and created an MD file with my diagram code.
The preview doesn't show anything.
What am I doing wrong?

**Comment by arichika** [comment]
@yemal 
This VSCode extension previews diagrams described in Mermaid syntax in files with the `.mmd` (**M**er **M**ai **D**) extension, and those described in MscGen syntax in files with the `.msc` extension. If you want to preview Mermaid syntax written inside a .md (**M**ark**d**own) file, you might consider using a separate extension like [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid).
